name: CI

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6

      - name: Set Xdebug mode
        run: echo "XDEBUG_MODE=coverage" >> $GITHUB_ENV

      - name: PHPUnit tests
        uses: php-actions/phpunit@v3
        with:
          version: '9.6.11'
          php_extensions: gd sqlite3 dom json mbstring libxml tokenizer xml xmlwriter zip xdebug
          configuration: phpunit.xml

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: log/coverage-cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'
      - name : Lauchn phpstan
        uses: php-actions/phpstan@v3
        with:
          path: lib/
          level: 7

      - name : Add markdown
        run : cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY



