name: CI

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: PHPUnit tests
      uses: php-actions/phpunit@v3
      with:
        php_extensions: "xdebug"
        coverage_clover: "coverage/clover.xml"